### ISSUE TITLE
Automate (clone) csvcubed build on csvcubed-pmd

### ISSUE THREAD

**Issue by canwaf** [GSS-Cogs/csvcubed-pmd#21]
Make sure the release process for csvcubed-pmd mirrors the csvcubed release process.

(Pick up dependabot bumps too.)

**Comment by CharlesRendle** [comment]
Pushing to review but do read the comment as I have not resolved the windows tests before leaving. I have [raised a new issue to deal with windows](https://app.zenhub.com/workspaces/features-squad-61b72275ac896c0010a1b00b/issues/gh/gss-cogs/csvcubed-pmd/23) but potentially it could be done in this ticket and that new one can be deleted.
