### ISSUE TITLE
Displaying behave tests results in a user friendly way on github actions

### ISSUE THREAD

**Issue by MuazzamChaud** [GSS-Cogs/csvcubed-pmd#3]
Probably need to write a python script which can run over the ouptut XML files from behave and remove the escape chars which the junit-compatible tool is unhappy reading.

- We can add the python file to the csvcubed-pmd repository. Try and make the script file independent of the main package so it shouldn't need any 3rd party dependencies from poetry (or need to be run in poetry at all).

- [ ] Make sure you consider how we'd reuse this script in a separate repository - so it should be easy for us to move it somewhere else when necessary.

**Comment by CharlesRendle** [comment]
Have added a few commits to the branch. Behave outputs still result in a not well formed xml.
Added the file path to the correct behave output files.
[This commit](https://github.com/GSS-Cogs/csvcubed-pmd/actions/runs/2584374967) removed some offending characters but not the ones from line 21

If the regex approach is taken, this should be transferable to a separate script and fulfil the ticket's requirements
